export const createRoomCopy = {
  es: {
    title: 'Crear Sala',
    desc: 'Sube un libro y comparte el PIN con otros.',
    bookPlaceholder: 'Título de la Sala',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de cierre',
    uploading: 'Subiendo...',
    createBtn: 'Crear Sala',
    errTitle: 'El título del libro es obligatorio.',
    errFile: 'Debes adjuntar un archivo PDF o ePub.',
    errFileSize: 'El archivo supera el límite de 50 MB.',
    errEndWithoutStart: 'No puedes definir una fecha de cierre sin una fecha de inicio.',
    errStartPast: 'La fecha de inicio no puede ser anterior a hoy.',
    errEndBeforeStart: 'La fecha de cierre debe ser posterior a la fecha de inicio.',
    errServer: 'El servidor no devolvió un ID válido.',
    emailPlaceholder: 'Ingrese correo electrónico',
    errEmail: 'El correo electrónico es obligatorio.',
    emailSent: 'Revisá el email para activar la sala',
  },
  en: {
    title: 'Create Room',
    desc: 'Upload a book and share the PIN with others.',
    bookPlaceholder: 'Room Title',
    startDate: 'Start date',
    endDate: 'End date',
    uploading: 'Uploading...',
    createBtn: 'Create Room',
    errTitle: 'Book title is required.',
    errFile: 'You must attach a PDF or ePub file.',
    errFileSize: 'File exceeds the 50 MB limit.',
    errEndWithoutStart: 'You cannot set an end date without a start date.',
    errStartPast: 'Start date cannot be before today.',
    errEndBeforeStart: 'End date must be after the start date.',
    errServer: 'Server did not return a valid ID.',
    emailPlaceholder: 'Your email address',
    errEmail: 'Email is required.',
    emailSent: 'Check your email to activate the room',
  },
} as const